version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive
    - misspell
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam
    revive:
      rules:
        - name: blank-imports
        - name: exported
        - name: unreachable-code
        - name: unused-parameter
