version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive
    - misspell
    - nilnil
    - nilerr
    - errorlint
    - durationcheck
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam
    revive:
      rules:
        - name: blank-imports
        - name: exported
        - name: unreachable-code
        - name: unused-parameter
