version: 2

builds:
  - main: ./cmd/wen
    binary: wen
    ldflags:
      - -s -w -X main.version={{ .Tag }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "wen_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "wen_checksums.txt"
  algorithm: sha256

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - "^release:"

release:
  github:
    owner: zachthieme
    name: wen
