version: 2

builds:
  - main: .
    binary: zdate
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "zdate_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "zdate_checksums.txt"
  algorithm: sha256

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
      - "^release:"

release:
  github:
    owner: zachthieme
    name: zdate
